### ISSUE TITLE
El usuario debe ingresar 5 números enteros, los cuales serán almacenados en una lista.

### ISSUE THREAD

**Issue by estx07** [estx07/proyecto-integrador#1]

**Comment by DaiaDubiel** [comment]
Done!

**Comment by estx07** [comment]
Daia, esta bien el código, pero necesito que le hagas un push al master desde tu rama con ese mismo código, ya que los compañeros van a buscar en programa.py el código de tu lista, asi puedo cerrar el issue de manera correcta. Por ahora no vamos a usar modulos, según consigna 👍.

**Comment by estx07** [comment]
Lista la Función inicial 👍
